# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the PostgreSQL driver
#   gem install pg
#
# Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: date_course_api_development
  username: <%= Rails.application.credentials.development[:database][:username] %>
  password: <%= Rails.application.credentials.development[:database][:password] %>
  host: <%= Rails.application.credentials.development[:database][:host] %>

test:
  <<: *default
  database: date_course_api_test
  username: <%= Rails.application.credentials.development[:database][:username] %>
  password: <%= Rails.application.credentials.development[:database][:password] %>
  host: <%= Rails.application.credentials.development[:database][:host] %>


production:
  <<: *default
  database: date_course_api_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>